### Get JWT token
POST http://localhost:8080/projeto/api/login/token
Content-Type: application/json

{
  "username": "cliente_User",
  "password": "pass"
}


### Who am I?
GET http://localhost:8080/projeto/api/login/claims
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDc5NzI3MzJ9.082-PN0UFd80l0dhEnXAgOGglPAWzsqNFD4gsy9cmfNMH77CpNKlT4KkunZYvj5ytS82J30DwtKI4Dy_Dwrr8UvmW0UWlhJ2Jpq5qTrV7LubfQfKsaxfae4gMtyRfqXWt9uGFC5HLIPBvqif_mZ9cZ47VlaiHZZRYD9folCYO3aDNkoV-IftZuGJnN1GamOiTMyI-ke2LAeD0Z3sqGRu_YGuVDjtFY0c5ux6HB0cgO1Png0S3-s57lucVaEwT5awE0Ruebwb_SmrbxPXs8Qnm0O6RzroUezBXxHKnPTisAT9B7OUIyAMv3_YnOEsNX3seWWpd2amWm-HFt6k4zEARQ


### Get cliente Details

GET http://localhost:8080/projeto/api/clientes/cliente_User
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDc5MDgyNTh9.dBP5UhTRG0CmzGeHAxcEyOpGPYrIWP1cwM12EtqqywkKSlcabodo2ncaCh9pCQWS4snssebd8R3g3wat-5mL0e79hA0zJsCg_lq1hYBiYW46KqtqAXI_B6ZOF2lE9MmMkuSkNyAea83IWmn7UEcrrnI61K0kxkmZCBN-xcH_PW1IyvaxHQX2qxBvRLFXkXyIGXbT5V4rurhWwyuZMuDztztQw8rZ7gaYKMurw0ZvYweJIkNkWvdnifn8JiMNFDJrQRrvvEeFt3C7JG8ft-1ksbJKpRUSz1JfQfUer4DJxlCKodFkdA2oXBkFmJf7yFgzkr5Ub4gj0Nc01ok3h80iXQ

### Get projetos cliente

GET http://localhost:8080/projeto/api/clientes/cliente_User/projetos/Projeto1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDc5NzI3MzJ9.082-PN0UFd80l0dhEnXAgOGglPAWzsqNFD4gsy9cmfNMH77CpNKlT4KkunZYvj5ytS82J30DwtKI4Dy_Dwrr8UvmW0UWlhJ2Jpq5qTrV7LubfQfKsaxfae4gMtyRfqXWt9uGFC5HLIPBvqif_mZ9cZ47VlaiHZZRYD9folCYO3aDNkoV-IftZuGJnN1GamOiTMyI-ke2LAeD0Z3sqGRu_YGuVDjtFY0c5ux6HB0cgO1Png0S3-s57lucVaEwT5awE0Ruebwb_SmrbxPXs8Qnm0O6RzroUezBXxHKnPTisAT9B7OUIyAMv3_YnOEsNX3seWWpd2amWm-HFt6k4zEARQ


###comentario
POST http://localhost:8080/projeto/api/clientes/cliente_User/projetos/Projeto1/comentario
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDY5MjY3ODZ9.UaNGsNsCCLVpqWaYNUVIBBGjnvk_FJtV_wJSKXLJNArMoALUu1d8DfgYqrhzJrKLTOttiKHt5E94IzxJv-lCsS5NVCFgFBRmbFU6DePBdz66CXQY_GGemm6Un2RwQ_uVo838uRrw_sEvEYdwkYqDy2dx2RXJSPz3yTxpFiwjDGe5C0jC3Jk_DKJpl4x41r4gq_kzM98Te6be9xltFkcKZeywKwWGeuR4kizGKF6-HJm4k_F81Y8TbtzEj16pMCcZ-vfCIuAG_RKB3PmQ1F7bojH7_ss0AYimelSYuG-U6tfA8BxpxqBmCGpFlTzMyQfG7Fxq3DVNnzK3r1OXGTsgzQ

{
  "comentario": "aceito as estruturas escolhidas"
}

###aceitar projeto

PUT http://localhost:8080/projeto/api/projetos/Projeto1/aceitar
Content-Type: application/json
