### Get JWT token
POST http://localhost:8080/projeto/api/login/token
Content-Type: application/json

{
  "username": "cliente_User",
  "password": "pass"
}


### Who am I?
GET http://localhost:8080/projeto/api/login/claims
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDY3NTIxNTh9.HQLHngDuLFpGgqpNDCH-yWYBL7UW34EgrSIYqvPBsvMffJOl-lsrH2-GQedPuAynQMKrbzVzOH_rJ6EDf-_YBDOcgskKhCmBA3Tlf8SQmXkpw9DW-aUCyuePCcHLJ30t2j9bVv2eudt4s9lpFvOf_GJu7T3vFz4cjfKTGgJqpjEzYWqqJXlPT-RxhRKrnbpV99gce3-65HN0ZDqch--5_VPsn9wy0UDyALp9dNGVjKlo4EcAujKIH4Jk7PdXMchi8qN6yvG44XenGJ-dwRyb7Kp66AioggpxxJE7gqXCQVQO65p-dY6ns8OWOUf1g35cAPlwYge52vzuf-RanbJbIA


### Get cliente Details

GET http://localhost:8080/projeto/api/clientes/cliente_User
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDY3NTIxNTh9.HQLHngDuLFpGgqpNDCH-yWYBL7UW34EgrSIYqvPBsvMffJOl-lsrH2-GQedPuAynQMKrbzVzOH_rJ6EDf-_YBDOcgskKhCmBA3Tlf8SQmXkpw9DW-aUCyuePCcHLJ30t2j9bVv2eudt4s9lpFvOf_GJu7T3vFz4cjfKTGgJqpjEzYWqqJXlPT-RxhRKrnbpV99gce3-65HN0ZDqch--5_VPsn9wy0UDyALp9dNGVjKlo4EcAujKIH4Jk7PdXMchi8qN6yvG44XenGJ-dwRyb7Kp66AioggpxxJE7gqXCQVQO65p-dY6ns8OWOUf1g35cAPlwYge52vzuf-RanbJbIA

### Get projetos cliente

GET http://localhost:8080/projeto/api/clientes/cliente_User/projetos/Projeto1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDY5MjY3ODZ9.UaNGsNsCCLVpqWaYNUVIBBGjnvk_FJtV_wJSKXLJNArMoALUu1d8DfgYqrhzJrKLTOttiKHt5E94IzxJv-lCsS5NVCFgFBRmbFU6DePBdz66CXQY_GGemm6Un2RwQ_uVo838uRrw_sEvEYdwkYqDy2dx2RXJSPz3yTxpFiwjDGe5C0jC3Jk_DKJpl4x41r4gq_kzM98Te6be9xltFkcKZeywKwWGeuR4kizGKF6-HJm4k_F81Y8TbtzEj16pMCcZ-vfCIuAG_RKB3PmQ1F7bojH7_ss0AYimelSYuG-U6tfA8BxpxqBmCGpFlTzMyQfG7Fxq3DVNnzK3r1OXGTsgzQ


###comentario
POST http://localhost:8080/projeto/api/clientes/cliente_User/projetos/Projeto1/comentario
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnRlX1VzZXIiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQ2xpZW50ZSJdLCJleHAiOjE2MDY5MjY3ODZ9.UaNGsNsCCLVpqWaYNUVIBBGjnvk_FJtV_wJSKXLJNArMoALUu1d8DfgYqrhzJrKLTOttiKHt5E94IzxJv-lCsS5NVCFgFBRmbFU6DePBdz66CXQY_GGemm6Un2RwQ_uVo838uRrw_sEvEYdwkYqDy2dx2RXJSPz3yTxpFiwjDGe5C0jC3Jk_DKJpl4x41r4gq_kzM98Te6be9xltFkcKZeywKwWGeuR4kizGKF6-HJm4k_F81Y8TbtzEj16pMCcZ-vfCIuAG_RKB3PmQ1F7bojH7_ss0AYimelSYuG-U6tfA8BxpxqBmCGpFlTzMyQfG7Fxq3DVNnzK3r1OXGTsgzQ

{
  "comentario": "aceito as estruturas escolhidas"
}