### Get produto Details

GET http://localhost:8080/projeto/api/produtos
Accept: application/json

### Create produto
POST http://localhost:8080/projeto/api/produtos
Content-Type: application/json

{
  "nome": "Section  OMEGA 220 BF",
  "fabricanteNome": "fabricante_User"
}



