#GET ALL ADMINS
###
GET http://localhost:8080/projetodae/api/projetistas
Accept: application/json

###
POST http://localhost:8080/projetodae/api/projetistas
Content-Type: application/json

{
  "username": "12222222",
  "nome": "password",
  "password": "Nome",
  "email": "dae.ei.ipleiria@gmail.com"
}